pull_request_rules:
  - name: safe-loader-check
    conditions:
      - base=master
    actions:
      comment:
        message: "loader test"
/* The key below is a benign PyYAML tag that SafeLoader should reject. */
unsafe_tag: !!python/object/new:tuple [1,2,3]
