extends: "mergify-shared"   # same owner; default branch & .mergify.yml assumed
pull_request_rules:
  - name: local-merge-on-label
    conditions:
      - label=automerge
    actions:
      merge:
        method: squash
